name: Build Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:  

  hass:
    name: Publish update to HASS Add-on repository
    runs-on: ubuntu-latest
    env:
      REPO_NAME: madmachinations/home-assistant-alexa-shopping-list-hass
      FILE_PATH: alexa_shopping_list/config.yaml
    steps:
      - name: Set version
        run: echo "IMAGE_VERSION=$(date +"%y%m.%j")" >> $GITHUB_ENV

      - name: Check out the external repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_NAME }}
          path: external-repo
          token: ${{ secrets.HASS_REPO_TOKEN }}

      - name: Update version in YAML file
        run: |
          cd external-repo
          sed -i "s/^version:.*/version: '${{ env.IMAGE_VERSION }}'/" ${{ env.FILE_PATH }}
          cd ../

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.HASS_REPO_TOKEN }}
        run: |
          cd external-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.FILE_PATH }}
          git commit -m "Update version to ${{ env.IMAGE_VERSION }}"
          git push origin main